# INTRODUCTION AND BASIC OPERATIONS

In [1]:
import numpy as np

In [2]:
lst = [1,2,3,4,5]
print(lst)

[1, 2, 3, 4, 5]


In [3]:
print('1D NP ARRRAY')
a = np.array([1,2,3,4,5])
print(a)


1D NP ARRRAY
[1 2 3 4 5]


In [4]:
print('2D ARRAY')
b = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(b)

2D ARRAY
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [5]:
print('3D ARRAY')
c = np.array([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]])
print(c)

3D ARRAY
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]


In [6]:
type(a)


numpy.ndarray

In [7]:
type(b)


numpy.ndarray

In [8]:
type(c)

numpy.ndarray

In [9]:
print(a.size)
print(b.size)
print(c.size)

5
10
15


# Numpy Functions np.ones,np.zeroes,np.empty

In [10]:
a = np.ones(4)
a  #will give an array of size 4 will 0. as elements

array([1., 1., 1., 1.])

In [11]:
a = np.zeros(4)
a #will give an array of size 4 will 0. as elements

array([0., 0., 0., 0.])

In [12]:
a = np.ones(4,dtype = int)
a #setting dtype as int hence will get an array of size 4 with value 1 

array([1, 1, 1, 1])

In [13]:
a = np.zeros(4,dtype=int)
a

array([0, 0, 0, 0])

In [14]:
a = np.empty(4,dtype = int)
a # will get an array of random values of type int

array([1701606756, 1869770784, 1701079414,  543236211])

In [15]:
a = np.ones((4,6))
a 

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [16]:
a = np.ones((4,6),dtype = int)
a 

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [17]:
a = np.ones((4,6),dtype = str)
a # well get a 2d array of 4 rows and 6 colums with 1 as string 

array([['1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1']], dtype='<U1')

In [18]:
a = np.zeros((4,6),dtype = str)
a # well get a 2d array of 4 rows and 6 colums with empty  string 

array([['', '', '', '', '', ''],
       ['', '', '', '', '', ''],
       ['', '', '', '', '', ''],
       ['', '', '', '', '', '']], dtype='<U1')

In [19]:
a = np.ones((4,5),dtype = bool)
a # for data type bool we get true for np.ones 

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [20]:
a = np.zeros((4,5),dtype = bool)
a # for data type bool we get true for np.zeros 

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

# Numpy Functions np.arange,np.flatten,np.ravel

In [21]:
# a = n.arange(start,end,step) 

In [23]:
a = np.arange(1,20) #by default step is 1
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [27]:
a = np.arange(1,20,2) # this will give odd numbers from 1 to 20
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [29]:
a = np.arange(2,20,2) #this will give even numbers from 2 to 20 lest element is not taken in arange function 
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [34]:
# a = {array name}.reshape((rows,columns))

In [35]:
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [36]:
# we have an array a having values from 2 - 18 lets convert this 1-D array to 2-D array of 3x3 3 rows and 3 columns

In [37]:
a = a.reshape((3,3))
a

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [53]:
b = np.array([
        [
            [1,2,3],
            [4,5,6],
            [7,8,9]
        ],
        [
            [10,11,12],
            [13,14,15],
            [16,17,18]
        ],
    [
            [19,20,21],
            [22,23,24],
            [25,26,27]
        
    ]
    
])

In [54]:
b.size

27

In [55]:
b.shape # to check the shape of array

(3, 3, 3)

In [61]:
b = b.reshape(3,3,2)  # Make sure the b.shape value which is 3,3,3 which is about 27 elements must fit with the values in rehsape provided else error will be shown 

ValueError: cannot reshape array of size 27 into shape (3,3,2)

In [62]:
b.reshape(27,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27]])

In [63]:
b.reshape(3,3,3)
b

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [64]:
b.reshape(9,3)
b

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [65]:
b.reshape(3,9) #b.flatten will convert 2D to 1D array
b

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [66]:
b.flatten() 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [67]:
b.reshape(3,3,3)
b

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [69]:
b.flatten() #b.flatten will convert 3D ARRAY TO 1d array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [70]:
# b.flatten function converts 2D and 3D arrays to 1D array

In [72]:
# b.ravel
b = np.array([
        [
            [1,2,3],
            [4,5,6],
            [7,8,9]
        ],
        [
            [10,11,12],
            [13,14,15],
            [16,17,18]
        ],
    [
            [19,20,21],
            [22,23,24],
            [25,26,27]
        
    ]
    
])





In [73]:
b

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [76]:
b = b.ravel() 
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [78]:
# ravel vs flatten

In [80]:
a = np.array([
            [1,2,3],
            [4,5,6],
            [7,8,9]
        ])

a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [81]:
f = a.flatten()
print('original ',a)
print('after a.flatten ',f)

original  [[1 2 3]
 [4 5 6]
 [7 8 9]]
after a.flatten  [1 2 3 4 5 6 7 8 9]


In [82]:
# lets change a value in flatten 
f[0] = 100
print('original ',a)
print('after a.flatten ',f)


original  [[1 2 3]
 [4 5 6]
 [7 8 9]]
after a.flatten  [100   2   3   4   5   6   7   8   9]


In [83]:
# as you can see there is no change in the original array


In [84]:
a = np.array([
            [1,2,3],
            [4,5,6],
            [7,8,9]
        ])

a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [85]:
r = a.ravel()
print('original ',a)
print('after a.flatten ',r)

original  [[1 2 3]
 [4 5 6]
 [7 8 9]]
after a.flatten  [1 2 3 4 5 6 7 8 9]


In [86]:
# lets change a value in ravel 
r[0] = 100
print('original ',a)
print('after a.flatten ',r)


original  [[100   2   3]
 [  4   5   6]
 [  7   8   9]]
after a.flatten  [100   2   3   4   5   6   7   8   9]


In [87]:
# there is a change in both original and raveled array 

### DIFFERENCE BETWEEN FLATTEN AND RAVEL

In [129]:
#ravel()

# Return only reference/view of the original array

# If you modify the array you would notice that the value of the original array also changes.

# Ravel is faster than flatten() as it does not occupy any memory.

# Ravel is a library-level function.

#flatten()

# Return copy of the original array

# If you modify any value of this array value of the original array is not affected.

# Flatten() is comparatively slower than ravel() as it occupies memory.

# Flatten is a method of an ndarray object.


# Mathematical Operations Numpy

In [177]:
a = np.arange(0,18,dtype = int).reshape(6,3)
b = np.arange(18,36,dtype = int).reshape(6,3)

In [178]:
print(a)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]
 [27 28 29]
 [30 31 32]
 [33 34 35]]


In [179]:
print("a+1",a+1)
print("a+b ",a+b)
print("np.add(a,b) ",np.add(a,b))

a+1 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
a+b  [[18 20 22]
 [24 26 28]
 [30 32 34]
 [36 38 40]
 [42 44 46]
 [48 50 52]]
np.add(a,b)  [[18 20 22]
 [24 26 28]
 [30 32 34]
 [36 38 40]
 [42 44 46]
 [48 50 52]]


In [180]:
# a+b or np.add(a,b)     will perform addition operation on two arrays of same size and shape both rows and columns must be 
#same for the operation to perform

In [181]:
print("a-b ",a-b)
print("np.subtract ",np.subtract(a,b)) 

a-b  [[-18 -18 -18]
 [-18 -18 -18]
 [-18 -18 -18]
 [-18 -18 -18]
 [-18 -18 -18]
 [-18 -18 -18]]
np.subtract  [[-18 -18 -18]
 [-18 -18 -18]
 [-18 -18 -18]
 [-18 -18 -18]
 [-18 -18 -18]
 [-18 -18 -18]]


In [185]:
print("a ",a)
print("b ",b)
print("a*b",a*b)  # a* b each element of a is geeting multitpled with each element of b at same position 
print("np.multiply ",np.multiply(a,b))

# for example a[0][0] which is 0 will be multiplied with b[0][0] which is 18 this is not MATRIX MULTIPLICATION

a  [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
b  [[18 19 20]
 [21 22 23]
 [24 25 26]
 [27 28 29]
 [30 31 32]
 [33 34 35]]
a*b [[  0  19  40]
 [ 63  88 115]
 [144 175 208]
 [243 280 319]
 [360 403 448]
 [495 544 595]]
np.multiply  [[  0  19  40]
 [ 63  88 115]
 [144 175 208]
 [243 280 319]
 [360 403 448]
 [495 544 595]]


In [187]:
print("a.shape", a.shape)
print("b.shape",b.shape)
print("a@b ",a@b) 
print("a.dot(b) ",a.dot(b))

#This will give the matrix multiplication of two arrays a and b but Its important that you check the shape of two arrays because for matrix multiplication
# the column of first array should be similar to row of second array and the size of result array will be ( row of first array X column of second array ) 

# LIKE THE ERROR IS GIVEN BELOW WHEN MULTIPLYING TWO ARRAY OF SIZE (6,3) (6,3) LETS RESHAPE AND TRY AGAIN 

a.shape (6, 3)
b.shape (6, 3)


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 6 is different from 3)

In [190]:
b = b.reshape(3,6)
print("a.shape", a.shape)
print("b.shape",b.shape)
print("a@b ",a@b) 
print("a.dot(b) ",a.dot(b))   # AS WE CAN SEE THE RESULT ARRAY IS OF SIZE 6 X 6 

a.shape (6, 3)
b.shape (3, 6)
a@b  [[  84   87   90   93   96   99]
 [ 300  312  324  336  348  360]
 [ 516  537  558  579  600  621]
 [ 732  762  792  822  852  882]
 [ 948  987 1026 1065 1104 1143]
 [1164 1212 1260 1308 1356 1404]]
a.dot(b)  [[  84   87   90   93   96   99]
 [ 300  312  324  336  348  360]
 [ 516  537  558  579  600  621]
 [ 732  762  792  822  852  882]
 [ 948  987 1026 1065 1104 1143]
 [1164 1212 1260 1308 1356 1404]]


In [195]:
b.max() # max value of array

35

In [196]:
b.min() #min vvalue of array

18

In [197]:
b.argmax() #max index of array

17

In [198]:
b.argmin() #min index of array 

0

In [203]:
np.sum(a) # gives value of sum of all elements in an array

153

In [210]:
print(a.shape)
print(a)

(6, 3)
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [204]:
np.sum(a,axis = 1) # axis  = 1 means sum of rows

array([ 3, 12, 21, 30, 39, 48])

In [206]:
np.sum(a,axis = 0) # axis = 0  means sum of each column

array([45, 51, 57])

In [220]:
np.mean(a) # give sum / total number of elements of an array  = mean of array (np.sum(array) /array.size)

8.5

In [221]:
np.sum(a) /a.size

8.5

In [223]:
np.sqrt(a) #give sqaure root of each element in array

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479],
       [3.46410162, 3.60555128, 3.74165739],
       [3.87298335, 4.        , 4.12310563]])

In [226]:
np.std(a) # give standard deviation of array

5.188127472091127

In [227]:
np.log(a) # give log for each of the element present in array 

C:\Users\Ujjawal Rajwanshi\AppData\Local\Temp\ipykernel_24328\1363168766.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a) # give log for each of the element present in array


array([[      -inf, 0.        , 0.69314718],
       [1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154],
       [2.19722458, 2.30258509, 2.39789527],
       [2.48490665, 2.56494936, 2.63905733],
       [2.7080502 , 2.77258872, 2.83321334]])