# INTRODUCTION AND BASIC OPERATIONS

In [58]:
import numpy as np

In [59]:
lst = [1,2,3,4,5]
print(lst)

[1, 2, 3, 4, 5]


In [60]:
print('1D NP ARRRAY')
a = np.array([1,2,3,4,5])
print(a)


1D NP ARRRAY
[1 2 3 4 5]


In [61]:
print('2D ARRAY')
b = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(b)

2D ARRAY
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [62]:
print('3D ARRAY')
c = np.array([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]])
print(c)

3D ARRAY
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]


In [63]:
type(a)


numpy.ndarray

In [64]:
type(b)


numpy.ndarray

In [65]:
type(c)

numpy.ndarray

In [66]:
print(a.size)
print(b.size)
print(c.size)

5
10
15


# Numpy Functions np.ones,np.zeroes,np.empty

In [67]:
a = np.ones(4)
a  #will give an array of size 4 will 0. as elements

array([1., 1., 1., 1.])

In [68]:
a = np.zeros(4)
a #will give an array of size 4 will 0. as elements

array([0., 0., 0., 0.])

In [69]:
a = np.ones(4,dtype = int)
a #setting dtype as int hence will get an array of size 4 with value 1 

array([1, 1, 1, 1])

In [70]:
a = np.zeros(4,dtype=int)
a

array([0, 0, 0, 0])

In [71]:
a = np.empty(4,dtype = int)
a # will get an array of random values of type int

array([-651673680,        479,          0,          0])

In [72]:
a = np.ones((4,6))
a 

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [73]:
a = np.ones((4,6),dtype = int)
a 

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [74]:
a = np.ones((4,6),dtype = str)
a # well get a 2d array of 4 rows and 6 colums with 1 as string 

array([['1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1']], dtype='<U1')

In [75]:
a = np.zeros((4,6),dtype = str)
a # well get a 2d array of 4 rows and 6 colums with empty  string 

array([['', '', '', '', '', ''],
       ['', '', '', '', '', ''],
       ['', '', '', '', '', ''],
       ['', '', '', '', '', '']], dtype='<U1')

In [76]:
a = np.ones((4,5),dtype = bool)
a # for data type bool we get true for np.ones 

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [77]:
a = np.zeros((4,5),dtype = bool)
a # for data type bool we get true for np.zeros 

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

# Numpy Functions np.arrange,np.flatten,np.ravel