# INTRODUCTION AND BASIC OPERATIONS

In [1]:
import numpy as np

In [2]:
lst = [1,2,3,4,5]
print(lst)

[1, 2, 3, 4, 5]


In [3]:
print('1D NP ARRRAY')
a = np.array([1,2,3,4,5])
print(a)


1D NP ARRRAY
[1 2 3 4 5]


In [4]:
print('2D ARRAY')
b = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(b)

2D ARRAY
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [5]:
print('3D ARRAY')
c = np.array([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]])
print(c)

3D ARRAY
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]


In [6]:
type(a)


numpy.ndarray

In [7]:
type(b)


numpy.ndarray

In [8]:
type(c)

numpy.ndarray

In [9]:
print(a.size)
print(b.size)
print(c.size)

5
10
15


# Numpy Functions np.ones,np.zeroes,np.empty

In [10]:
a = np.ones(4)
a  #will give an array of size 4 will 0. as elements

array([1., 1., 1., 1.])

In [11]:
a = np.zeros(4)
a #will give an array of size 4 will 0. as elements

array([0., 0., 0., 0.])

In [12]:
a = np.ones(4,dtype = int)
a #setting dtype as int hence will get an array of size 4 with value 1 

array([1, 1, 1, 1])

In [13]:
a = np.zeros(4,dtype=int)
a

array([0, 0, 0, 0])

In [14]:
a = np.empty(4,dtype = int)
a # will get an array of random values of type int

array([1344282656, 1835102817, 1919251557,  538970739])

In [15]:
a = np.ones((4,6))
a 

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [16]:
a = np.ones((4,6),dtype = int)
a 

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [17]:
a = np.ones((4,6),dtype = str)
a # well get a 2d array of 4 rows and 6 colums with 1 as string 

array([['1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1']], dtype='<U1')

In [18]:
a = np.zeros((4,6),dtype = str)
a # well get a 2d array of 4 rows and 6 colums with empty  string 

array([['', '', '', '', '', ''],
       ['', '', '', '', '', ''],
       ['', '', '', '', '', ''],
       ['', '', '', '', '', '']], dtype='<U1')

In [19]:
a = np.ones((4,5),dtype = bool)
a # for data type bool we get true for np.ones 

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [20]:
a = np.zeros((4,5),dtype = bool)
a # for data type bool we get true for np.zeros 

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

# Numpy Functions np.arange,np.flatten,np.ravel

In [21]:
# a = n.arange(start,end,step) 

In [22]:
a = np.arange(1,20) #by default step is 1
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [23]:
a = np.arange(1,20,2) # this will give odd numbers from 1 to 20
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [24]:
a = np.arange(2,20,2) #this will give even numbers from 2 to 20 lest element is not taken in arange function 
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [25]:
# a = {array name}.reshape((rows,columns))

In [26]:
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [27]:
# we have an array a having values from 2 - 18 lets convert this 1-D array to 2-D array of 3x3 3 rows and 3 columns

In [28]:
a = a.reshape((3,3))
a

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [29]:
b = np.array([
        [
            [1,2,3],
            [4,5,6],
            [7,8,9]
        ],
        [
            [10,11,12],
            [13,14,15],
            [16,17,18]
        ],
    [
            [19,20,21],
            [22,23,24],
            [25,26,27]
        
    ]
    
])

In [30]:
b.size

27

In [31]:
b.shape # to check the shape of array

(3, 3, 3)

In [32]:
b = b.reshape(3,3,2)  # Make sure the b.shape value which is 3,3,3 which is about 27 elements must fit with the values in rehsape provided else error will be shown 

ValueError: cannot reshape array of size 27 into shape (3,3,2)

In [ ]:
b.reshape(27,1)

In [ ]:
b.reshape(3,3,3)
b

In [ ]:
b.reshape(9,3)
b

In [ ]:
b.reshape(3,9) #b.flatten will convert 2D to 1D array
b

In [ ]:
b.flatten() 

In [ ]:
b.reshape(3,3,3)
b

In [ ]:
b.flatten() #b.flatten will convert 3D ARRAY TO 1d array

In [ ]:
# b.flatten function converts 2D and 3D arrays to 1D array

In [ ]:
# b.ravel
b = np.array([
        [
            [1,2,3],
            [4,5,6],
            [7,8,9]
        ],
        [
            [10,11,12],
            [13,14,15],
            [16,17,18]
        ],
    [
            [19,20,21],
            [22,23,24],
            [25,26,27]
        
    ]
    
])





In [ ]:
b

In [ ]:
b = b.ravel() 
b

In [ ]:
# ravel vs flatten

In [ ]:
a = np.array([
            [1,2,3],
            [4,5,6],
            [7,8,9]
        ])

a

In [ ]:
f = a.flatten()
print('original ',a)
print('after a.flatten ',f)

In [ ]:
# lets change a value in flatten 
f[0] = 100
print('original ',a)
print('after a.flatten ',f)


In [ ]:
# as you can see there is no change in the original array


In [ ]:
a = np.array([
            [1,2,3],
            [4,5,6],
            [7,8,9]
        ])

a

In [ ]:
r = a.ravel()
print('original ',a)
print('after a.flatten ',r)

In [ ]:
# lets change a value in ravel 
r[0] = 100
print('original ',a)
print('after a.flatten ',r)


In [ ]:
# there is a change in both original and raveled array 

### DIFFERENCE BETWEEN FLATTEN AND RAVEL

In [ ]:
#ravel()

# Return only reference/view of the original array

# If you modify the array you would notice that the value of the original array also changes.

# Ravel is faster than flatten() as it does not occupy any memory.

# Ravel is a library-level function.

#flatten()

# Return copy of the original array

# If you modify any value of this array value of the original array is not affected.

# Flatten() is comparatively slower than ravel() as it occupies memory.

# Flatten is a method of an ndarray object.


# Mathematical Operations Numpy

In [ ]:
a = np.arange(0,18,dtype = int).reshape(6,3)
b = np.arange(18,36,dtype = int).reshape(6,3)

In [ ]:
print(a)
print(b)

In [ ]:
print("a+1",a+1)
print("a+b ",a+b)
print("np.add(a,b) ",np.add(a,b))

In [ ]:
# a+b or np.add(a,b)     will perform addition operation on two arrays of same size and shape both rows and columns must be 
#same for the operation to perform

In [ ]:
print("a-b ",a-b)
print("np.subtract ",np.subtract(a,b)) 

In [ ]:
print("a ",a)
print("b ",b)
print("a*b",a*b)  # a* b each element of a is geeting multitpled with each element of b at same position 
print("np.multiply ",np.multiply(a,b))

# for example a[0][0] which is 0 will be multiplied with b[0][0] which is 18 this is not MATRIX MULTIPLICATION

In [ ]:
print("a.shape", a.shape)
print("b.shape",b.shape)
print("a@b ",a@b) 
print("a.dot(b) ",a.dot(b))

#This will give the matrix multiplication of two arrays a and b but Its important that you check the shape of two arrays because for matrix multiplication
# the column of first array should be similar to row of second array and the size of result array will be ( row of first array X column of second array ) 

# LIKE THE ERROR IS GIVEN BELOW WHEN MULTIPLYING TWO ARRAY OF SIZE (6,3) (6,3) LETS RESHAPE AND TRY AGAIN 

In [ ]:
b = b.reshape(3,6)
print("a.shape", a.shape)
print("b.shape",b.shape)
print("a@b ",a@b) 
print("a.dot(b) ",a.dot(b))   # AS WE CAN SEE THE RESULT ARRAY IS OF SIZE 6 X 6 

In [ ]:
b.max() # max value of array

In [ ]:
b.min() #min vvalue of array

In [ ]:
b.argmax() #max index of array

In [ ]:
b.argmin() #min index of array 

In [ ]:
np.sum(a) # gives value of sum of all elements in an array

In [ ]:
print(a.shape)
print(a)

In [ ]:
np.sum(a,axis = 1) # axis  = 1 means sum of rows

In [ ]:
np.sum(a,axis = 0) # axis = 0  means sum of each column

In [ ]:
np.mean(a) # give sum / total number of elements of an array  = mean of array (np.sum(array) /array.size)

In [ ]:
np.sum(a) /a.size

In [ ]:
np.sqrt(a) #give sqaure root of each element in array

In [ ]:
np.std(a) # give standard deviation of array

In [ ]:
np.log(a) # give log for each of the element present in array 

# TRIGNOMETRIC OPERATIONS

In [ ]:
import numpy as np

In [ ]:
np.pi #np.pi = π = 180 degrees

In [ ]:
a = np.sin(np.pi/6) # giving sin 30 degree which is 1/2 
a

In [ ]:
a = np.cos(0) # cos 0 is 1
a

In [ ]:
a = np.tan(np.pi/2) # tan 90 = infi hence it is giving a high value
a

# Using Matplotlib

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
a = np.arange(1,11,2)
b = np.arange(2,11,2)
print(a)
print(b)

In [ ]:
plt.figure(figsize = (6,6)).add_axes([0,9,0,9])
plt.scatter(a,b)
plt.show()

In [ ]:
plt.plot([1,2,3,5,6], [1, 2, 3, 4, 6],'r--')
plt.axis([0, 7, 0, 7])

In [ ]:
x_sin = np.arange(0,2*np.pi,0.1)
y_sin = np.sin(x_sin)


print("x_sin or values of angles from 0 to 360 degrees " ,x_sin)
print("y_sin sin of respective x_sin values ",y_sin)

plt.figure(figsize = (6,6))
plt.plot(x_sin,y_sin)


In [ ]:
x_cos = np.arange(0,2*np.pi,0.1)
y_cos = np.cos(x_cos)


print("x_sin or values of angles from 0 to 360 degrees " ,x_cos)
print("y_sin sin of respective x_sin values ",y_cos)

plt.figure(figsize = (6,6))
plt.plot(x_cos,y_cos)

In [ ]:
x_tan = np.arange(0,2*np.pi,0.1)
y_tan = np.tan(x_tan)


print("x_sin or values of angles from 0 to 360 degrees " ,x_tan)
print("y_sin sin of respective x_sin values ",y_tan)

plt.figure(figsize = (6,6))
plt.plot(x_tan,y_tan)

plt.figure(figsize = (19,19))
plt.subplot(6,6,1)
plt.plot(x_sin, y_sin,'r-')

plt.subplot(6,6,2)
plt.plot(x_cos,y_cos,'b-')

plt.subplot(6,6,3)
plt.plot(x_tan,y_tan,'g-')
plt.show()

## RANDOM FUNCTION

In [ ]:
np.random.random(1) # will give you a random value everytime run

In [ ]:
np.random.random(2) # will give you a list of size 2 radom values

In [ ]:
np.random.random(3)

In [ ]:
np.random.random((2,2)) # will give a 2d array of random values 

In [ ]:
np.random.randint(1,10) # will generate a random int value from 1, 10 

In [ ]:
np.random.randint(1,10 , 2)  # will generate a array of size 2 of random int value from 1,10 

In [ ]:
np.random.randint(1,10 , (2,3))  # will give a 2d array of random int values of shape 2 X 3

In [ ]:
np.random.randint(1,10 , (2,3,4))

In [ ]:
np.random.rand(2,2)

In [ ]:
np.random.randn(2,2) # it can generate negative random numbers as well

In [ ]:
np.random.choice([1,2,3,4,5]) # gives a random value from the provided list 

### Difference between np.random.random vs np.random.rand vs np.random.randn ?