# INTRODUCTION AND BASIC OPERATIONS

In [1]:
import numpy as np

In [2]:
lst = [1,2,3,4,5]
print(lst)

[1, 2, 3, 4, 5]


In [3]:
print('1D NP ARRRAY')
a = np.array([1,2,3,4,5])
print(a)


1D NP ARRRAY
[1 2 3 4 5]


In [4]:
print('2D ARRAY')
b = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(b)

2D ARRAY
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [5]:
print('3D ARRAY')
c = np.array([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]])
print(c)

3D ARRAY
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]


In [6]:
type(a)


numpy.ndarray

In [7]:
type(b)


numpy.ndarray

In [8]:
type(c)

numpy.ndarray

In [9]:
print(a.size)
print(b.size)
print(c.size)

5
10
15


# Numpy Functions np.ones,np.zeroes,np.empty

In [10]:
a = np.ones(4)
a  #will give an array of size 4 will 0. as elements

array([1., 1., 1., 1.])

In [11]:
a = np.zeros(4)
a #will give an array of size 4 will 0. as elements

array([0., 0., 0., 0.])

In [12]:
a = np.ones(4,dtype = int)
a #setting dtype as int hence will get an array of size 4 with value 1 

array([1, 1, 1, 1])

In [13]:
a = np.zeros(4,dtype=int)
a

array([0, 0, 0, 0])

In [14]:
a = np.empty(4,dtype = int)
a # will get an array of random values of type int

array([1701606756, 1869770784, 1701079414,  543236211])

In [15]:
a = np.ones((4,6))
a 

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [16]:
a = np.ones((4,6),dtype = int)
a 

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [17]:
a = np.ones((4,6),dtype = str)
a # well get a 2d array of 4 rows and 6 colums with 1 as string 

array([['1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1']], dtype='<U1')

In [18]:
a = np.zeros((4,6),dtype = str)
a # well get a 2d array of 4 rows and 6 colums with empty  string 

array([['', '', '', '', '', ''],
       ['', '', '', '', '', ''],
       ['', '', '', '', '', ''],
       ['', '', '', '', '', '']], dtype='<U1')

In [19]:
a = np.ones((4,5),dtype = bool)
a # for data type bool we get true for np.ones 

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [20]:
a = np.zeros((4,5),dtype = bool)
a # for data type bool we get true for np.zeros 

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

# Numpy Functions np.arange,np.flatten,np.ravel

In [21]:
# a = n.arange(start,end,step) 

In [23]:
a = np.arange(1,20) #by default step is 1
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [27]:
a = np.arange(1,20,2) # this will give odd numbers from 1 to 20
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [29]:
a = np.arange(2,20,2) #this will give even numbers from 2 to 20 lest element is not taken in arange function 
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [34]:
# a = {array name}.reshape((rows,columns))

In [35]:
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [36]:
# we have an array a having values from 2 - 18 lets convert this 1-D array to 2-D array of 3x3 3 rows and 3 columns

In [37]:
a = a.reshape((3,3))
a

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [53]:
b = np.array([
        [
            [1,2,3],
            [4,5,6],
            [7,8,9]
        ],
        [
            [10,11,12],
            [13,14,15],
            [16,17,18]
        ],
    [
            [19,20,21],
            [22,23,24],
            [25,26,27]
        
    ]
    
])

In [54]:
b.size

27

In [55]:
b.shape # to check the shape of array

(3, 3, 3)

In [61]:
b = b.reshape(3,3,2)  # Make sure the b.shape value which is 3,3,3 which is about 27 elements must fit with the values in rehsape provided else error will be shown 

ValueError: cannot reshape array of size 27 into shape (3,3,2)

In [62]:
b.reshape(27,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27]])

In [63]:
b.reshape(3,3,3)
b

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [64]:
b.reshape(9,3)
b

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [65]:
b.reshape(3,9) #b.flatten will convert 2D to 1D array
b

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [66]:
b.flatten() 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [67]:
b.reshape(3,3,3)
b

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [69]:
b.flatten() #b.flatten will convert 3D ARRAY TO 1d array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [70]:
# b.flatten function converts 2D and 3D arrays to 1D array

In [72]:
# b.ravel
b = np.array([
        [
            [1,2,3],
            [4,5,6],
            [7,8,9]
        ],
        [
            [10,11,12],
            [13,14,15],
            [16,17,18]
        ],
    [
            [19,20,21],
            [22,23,24],
            [25,26,27]
        
    ]
    
])





In [73]:
b

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [76]:
b = b.ravel() 
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [78]:
# ravel vs flatten

In [80]:
a = np.array([
            [1,2,3],
            [4,5,6],
            [7,8,9]
        ])

a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [81]:
f = a.flatten()
print('original ',a)
print('after a.flatten ',f)

original  [[1 2 3]
 [4 5 6]
 [7 8 9]]
after a.flatten  [1 2 3 4 5 6 7 8 9]


In [82]:
# lets change a value in flatten 
f[0] = 100
print('original ',a)
print('after a.flatten ',f)


original  [[1 2 3]
 [4 5 6]
 [7 8 9]]
after a.flatten  [100   2   3   4   5   6   7   8   9]


In [83]:
# as you can see there is no change in the original array


In [84]:
a = np.array([
            [1,2,3],
            [4,5,6],
            [7,8,9]
        ])

a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [85]:
r = a.ravel()
print('original ',a)
print('after a.flatten ',r)

original  [[1 2 3]
 [4 5 6]
 [7 8 9]]
after a.flatten  [1 2 3 4 5 6 7 8 9]


In [86]:
# lets change a value in ravel 
r[0] = 100
print('original ',a)
print('after a.flatten ',r)


original  [[100   2   3]
 [  4   5   6]
 [  7   8   9]]
after a.flatten  [100   2   3   4   5   6   7   8   9]


In [87]:
# there is a change in both original and raveled array 

### DIFFERENCE BETWEEN FLATTEN AND RAVEL

In [89]:
#ravel()

# Return only reference/view of the original array

# If you modify the array you would notice that the value of the original array also changes.

# Ravel is faster than flatten() as it does not occupy any memory.

# Ravel is a library-level function.

#flatten()

# Return copy of the original array

# If you modify any value of this array value of the original array is not affected.

# Flatten() is comparatively slower than ravel() as it occupies memory.

# Flatten is a method of an ndarray object.
